=== vs49688/CrocUtils/resources/map.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
	"mapstring": {
	  "type": "string",
	  "maxLength": 255
	},
	"uint16": {
	  "type": "integer",
	  "minimum": 0,
	  "maximum": 65535
	},
	"uint32": {
	  "type": "integer",
	  "minimum": 0,
	  "maximum": 4294967295
	},
	"vector3": {
	  "type": "array",
	  "minLength": 3,
	  "maxLength": 3,
	  "items": {
		"type": "number"
	  }
	},
	"colour": {
	  "type": "array",
	  "minLength": 3,
	  "maxLength": 3,
	  "items": {
		"type": "integer",
		"minimum": 0,
		"maximum": 255
	  }
	},
	"track": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"yr": {
		  "type": "number"
		},
		"index": {
		  "$ref": "#/definitions/uint16"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"yr",
		"index"
	  ]
	},
	"waypoint": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"var": {
		  "$ref": "#/definitions/uint32"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"var"
	  ]
	},
	"strategy": {
	  "type": "object",
	  "properties": {
		"params": {
		  "type": "array",
		  "minLength": 8,
		  "maxLength": 8,
		  "items": {
			"$ref": "#/definitions/uint32"
		  }
		},
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"rotation": {
		  "$ref": "#/definitions/vector3"
		},
		"name": {
		  "type": "string",
		  "minLength": 1,
		  "maxLength": 255
		},
		"waypoints": {
		  "type": "array",
		  "items": {
			"$ref": "#/definitions/waypoint"
		  }
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"params",
		"position",
		"rotation",
		"name",
		"waypoints"
	  ]
	},
	"door": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"level": {
		  "$ref": "#/definitions/uint16"
		},
		"sublevel": {
		  "$ref": "#/definitions/uint16"
		},
		"flags": {
		  "type": "array",
		  "items": {
			"enum": [
			  "normal",
			  "floor",
			  "ceiling",
			  "start",
			  "final"
			]
		  },
		  "uniqueItems": true
		},
		"id": {
		  "$ref": "#/definitions/uint16"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"level",
		"sublevel",
		"flags",
		"id"
	  ]
	},
	"point_light": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"colour": {
		  "$ref": "#/definitions/colour"
		},
		"fade_from": {
		  "type": "number"
		},
		"fade_to": {
		  "type": "number"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"colour",
		"fade_from",
		"fade_to"
	  ]
	},
	"direct_light": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"colour": {
		  "$ref": "#/definitions/colour"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"colour"
	  ]
	}
  },
  "type": "object",
  "properties": {
	"_meta": {
	  "type": "object",
	  "properties": {
		"version": {
		  "type": "integer"
		},
		"format": {
		  "enum": [
			"normal",
			"v12",
			"v12_old",
			"v12_old_noambient"
		  ]
		},
		"level": {
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 999
		},
		"sublevel": {
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 99
		},
		"checksum": {
		  "type": "integer"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"version",
		"format",
		"level",
		"sublevel",
		"checksum"
	  ]
	},
	"path": {
	  "$ref": "#/definitions/mapstring"
	},
	"name": {
	  "$ref": "#/definitions/mapstring"
	},
	"width": {
	  "$ref": "#/definitions/uint16"
	},
	"height": {
	  "$ref": "#/definitions/uint16"
	},
	"depth": {
	  "$ref": "#/definitions/uint16"
	},
	"style": {
	  "oneOf": [
		{
		  "enum": [
			"ice",
			"water",
			"castle",
			"desert",
			"cave",
			"wood",
			"dungeon",
			"boss1",
			"boss2",
			"boss3",
			"boss4",
			"boss5",
			"boss6",
			"boss7",
			"boss8",
			"boss9",
			"island1",
			"island2",
			"island3",
			"island4",
			"island5",
			"iceslide",
			"boulder",
			"icecave"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 24
		}
	  ]
	},
	"flags": {
	  "$ref": "#/definitions/uint32"
	},
	"cd_track": {
	  "$ref": "#/definitions/uint32"
	},
	"background": {
	  "$ref": "#/definitions/uint32"
	},
	"effect": {
	  "oneOf": [
		{
		  "enum": [
			"none",
			"snow",
			"fog",
			"torch",
			"torch_lightning",
			"torch_big",
			"torch_big_lightning",
			"dark",
			"snow_small",
			"snow_island",
			"torch_giant"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 15
		}
	  ]
	},
	"wait": {
	  "$ref": "#/definitions/uint32"
	},
	"ambience": {
	  "oneOf": [
		{
		  "enum": [
			"none",
			"bird",
			"drip",
			"nght",
			"watr",
			"crwd",
			"lava",
			"tunl",
			"ice1",
			"tomb",
			"des1",
			"dcav",
			"slde",
			"cast",
			"dngn",
			"ice2",
			"clwd",
			"whal",
			"moat",
			"dusk",
			"wind",
			"cica",
			"dant"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 22
		}
	  ]
	},
	"start_rotation": {
	  "type": "number"
	},
	"tracks": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/track"
	  }
	},
	"strats": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/strategy"
	  }
	},
	"doors": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/door"
	  }
	},
	"point_lights": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/point_light"
	  }
	},
	"direct_lights": {
	  "type": "array",
	  "minItems": 3,
	  "maxItems": 3,
	  "items": {
		"$ref": "#/definitions/direct_light"
	  }
	},
	"ambient_colour": {
	  "$ref": "#/definitions/colour"
	},
	"$schema": {
	  "type": "string"
	}
  },
  "additionalProperties": false,
  "required": [
	"path",
	"name",
	"width",
	"height",
	"depth",
	"style",
	"flags",
	"cd_track",
	"background",
	"effect",
	"wait",
	"ambience",
	"start_rotation",
	"tracks",
	"strats",
	"doors",
	"point_lights",
	"direct_lights",
	"ambient_colour"
  ]
}

=== vs49688/CrocUtils/resources/maps/json/beta012/MP020_00.json
{
	"_meta":	{
		"version":	12,
		"format":	"v12_old",
		"level":	20,
		"sublevel":	0,
		"checksum":	0
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\ISLAND2\\LEVEL1\\MAP1.MAP",
	"name":	"Default New Map",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"ice",
	"flags":	4,
	"cd_track":	0,
	"background":	3,
	"effect":	"snow",
	"wait":	16,
	"ambience":	"none",
	"start_rotation":	0.002685546875,
	"tracks":	[{
			"position":	[3, 0, 2],
			"yr":	0.25,
			"index":	22
		}, {
			"position":	[4, 0, 2],
			"yr":	0,
			"index":	23
		}, {
			"position":	[5, 0, 2],
			"yr":	0,
			"index":	22
		}, {
			"position":	[3, 0, 3],
			"yr":	0.25,
			"index":	23
		}, {
			"position":	[4, 0, 3],
			"yr":	0,
			"index":	1
		}, {
			"position":	[5, 0, 3],
			"yr":	0.75,
			"index":	23
		}, {
			"position":	[3, 0, 4],
			"yr":	0.25,
			"index":	67
		}, {
			"position":	[4, 0, 4],
			"yr":	0,
			"index":	3
		}, {
			"position":	[5, 0, 4],
			"yr":	0.75,
			"index":	68
		}, {
			"position":	[3, 0, 5],
			"yr":	0.25,
			"index":	39
		}, {
			"position":	[4, 0, 5],
			"yr":	0,
			"index":	2
		}, {
			"position":	[5, 0, 5],
			"yr":	0.75,
			"index":	39
		}, {
			"position":	[0, 0, 6],
			"yr":	0,
			"index":	80
		}, {
			"position":	[1, 0, 6],
			"yr":	0,
			"index":	25
		}, {
			"position":	[2, 0, 6],
			"yr":	0,
			"index":	43
		}, {
			"position":	[3, 0, 6],
			"yr":	0,
			"index":	41
		}, {
			"position":	[4, 0, 6],
			"yr":	0.25,
			"index":	10
		}, {
			"position":	[5, 0, 6],
			"yr":	0.75,
			"index":	41
		}, {
			"position":	[6, 0, 6],
			"yr":	0,
			"index":	104
		}, {
			"position":	[7, 0, 6],
			"yr":	0,
			"index":	25
		}, {
			"position":	[8, 0, 6],
			"yr":	0.75,
			"index":	80
		}, {
			"position":	[0, 0, 7],
			"yr":	0.25,
			"index":	80
		}, {
			"position":	[1, 0, 7],
			"yr":	0.5,
			"index":	25
		}, {
			"position":	[2, 0, 7],
			"yr":	0.5,
			"index":	104
		}, {
			"position":	[3, 0, 7],
			"yr":	0.25,
			"index":	41
		}, {
			"position":	[4, 0, 7],
			"yr":	0.75,
			"index":	10
		}, {
			"position":	[5, 0, 7],
			"yr":	0.5,
			"index":	41
		}, {
			"position":	[6, 0, 7],
			"yr":	0.5,
			"index":	43
		}, {
			"position":	[7, 0, 7],
			"yr":	0.5,
			"index":	25
		}, {
			"position":	[8, 0, 7],
			"yr":	0.5,
			"index":	80
		}, {
			"position":	[3, 0, 8],
			"yr":	0.25,
			"index":	39
		}, {
			"position":	[4, 0, 8],
			"yr":	0,
			"index":	2
		}, {
			"position":	[5, 0, 8],
			"yr":	0.75,
			"index":	39
		}, {
			"position":	[3, 0, 9],
			"yr":	0.25,
			"index":	68
		}, {
			"position":	[4, 0, 9],
			"yr":	0.5,
			"index":	3
		}, {
			"position":	[5, 0, 9],
			"yr":	0.75,
			"index":	67
		}, {
			"position":	[3, 0, 10],
			"yr":	0.5,
			"index":	22
		}, {
			"position":	[4, 0, 10],
			"yr":	0.5,
			"index":	114
		}, {
			"position":	[5, 0, 10],
			"yr":	0.75,
			"index":	22
		}, {
			"position":	[4, 0, 11],
			"yr":	0.5,
			"index":	111
		}],
	"strats":	[{
			"params":	[0, 0, 0, 1310720, 39320, 0, 0, 0],
			"position":	[4, 0, 4.83123779296875],
			"rotation":	[0, 0.3330078125, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 1310720, 39320, 0, 0, 0],
			"position":	[4, 0, 4.83123779296875],
			"rotation":	[0, 0.666015625, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 1310720, 39320, 0, 0, 0],
			"position":	[4, 0, 4.83123779296875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 1310720, 39320, 0, 0, 0],
			"position":	[4, 0, 8.26249694824219],
			"rotation":	[0, 0, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 1310720, 39320, 0, 0, 0],
			"position":	[4, 0, 8.26249694824219],
			"rotation":	[0, 0.666015625, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 1310720, 39320, 0, 0, 0],
			"position":	[4, 0, 8.26249694824219],
			"rotation":	[0, 0.3330078125, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4, 0, 4.79998779296875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformStepStone",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4, 0, 8.26249694824219],
			"rotation":	[0, 0, 0],
			"name":	"PlatformStepStone",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.8999786376953125, 0.399993896484375, 6.5],
			"rotation":	[0, 0.749267578125, 0],
			"name":	"ForestMonkBarStr",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.15496826171875, 0.399993896484375, 6.498748779296875],
			"rotation":	[0, 0.749267578125, 0],
			"name":	"ForestMonkBarStr",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.40997314453125, 0.399993896484375, 6.5],
			"rotation":	[0, 0.749267578125, 0],
			"name":	"ForestMonkBarStr",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.6449737548828125, 0.399993896484375, 6.5],
			"rotation":	[0, 0.249755859375, 0],
			"name":	"ForestMonkBarStr",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[5.3899688720703125, 0.399993896484375, 6.5],
			"rotation":	[0, 0.249755859375, 0],
			"name":	"ForestMonkBarStr",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[5.944976806640625, 0.399993896484375, 6.5012359619140625],
			"rotation":	[0, 0.249755859375, 0],
			"name":	"ForestMonkBarEnd",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[1.8549652099609375, 0.399993896484375, 6.498748779296875],
			"rotation":	[0, 0.749267578125, 0],
			"name":	"ForestMonkBarEnd",
			"waypoints":	[]
		}, {
			"params":	[13107, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.5, 0, 6.53125],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[13107, 0, 0, 0, 0, 0, 0, 0],
			"position":	[5.5, 0, 6.53125],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[13107, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.5, 0, 6.5],
			"rotation":	[0, 0, 0],
			"name":	"Crystal_B",
			"waypoints":	[]
		}, {
			"params":	[13107, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.5, 0, 6.5],
			"rotation":	[0, 0, 0],
			"name":	"Crystal_O",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[6.9999847412109375, 0, 6.5],
			"rotation":	[0, 0.874267578125, 0],
			"name":	"SmashBlockGobbo",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[0.274993896484375, 0, 6.5],
			"rotation":	[0, 0.902099609375, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4, 0, 10.53125],
			"rotation":	[0, 0.49951171875, 0],
			"name":	"NormalDoor",
			"waypoints":	[]
		}],
	"doors":	[{
			"position":	[3, 0, 2],
			"level":	0,
			"sublevel":	0,
			"flags":	[],
			"id":	0
		}, {
			"position":	[3, 0, 3],
			"level":	0,
			"sublevel":	0,
			"flags":	[],
			"id":	0
		}, {
			"position":	[4, 0, 3],
			"level":	0,
			"sublevel":	0,
			"flags":	["start"],
			"id":	0
		}, {
			"position":	[4, 0, 11],
			"level":	20,
			"sublevel":	1,
			"flags":	["normal"],
			"id":	0
		}],
	"point_lights":	[],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[64, 64, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 128]
		}, {
			"position":	[0, 0.5, -0.000244140625],
			"colour":	[43, 43, 43]
		}],
	"ambient_colour":	[64, 64, 64]
}

=== vs49688/CrocUtils/resources/maps/json/slus00530/MP036_04.json
{
	"_meta":	{
		"version":	20,
		"format":	"normal",
		"level":	0,
		"sublevel":	4,
		"checksum":	51241
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\DESERT\\LEVEL6\\MAP5.MAP",
	"name":	"final level 5",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"desert",
	"flags":	4,
	"cd_track":	28,
	"background":	29,
	"effect":	"none",
	"wait":	0,
	"ambience":	"tomb",
	"start_rotation":	0.244140625,
	"tracks":	[{
			"position":	[9, 2, 1],
			"yr":	0.5,
			"index":	77
		}, {
			"position":	[10, 2, 1],
			"yr":	0.5,
			"index":	43
		}, {
			"position":	[11, 2, 1],
			"yr":	0.25,
			"index":	77
		}, {
			"position":	[9, 2, 2],
			"yr":	0.75,
			"index":	43
		}, {
			"position":	[10, 2, 2],
			"yr":	0,
			"index":	64
		}, {
			"position":	[11, 2, 2],
			"yr":	0.25,
			"index":	43
		}, {
			"position":	[9, 2, 3],
			"yr":	0.75,
			"index":	77
		}, {
			"position":	[10, 2, 3],
			"yr":	0,
			"index":	43
		}, {
			"position":	[11, 2, 3],
			"yr":	0,
			"index":	77
		}, {
			"position":	[9, 2, 4],
			"yr":	0.5,
			"index":	77
		}, {
			"position":	[10, 2, 4],
			"yr":	0.5,
			"index":	43
		}, {
			"position":	[11, 2, 4],
			"yr":	0.25,
			"index":	77
		}, {
			"position":	[9, 2, 5],
			"yr":	0.75,
			"index":	43
		}, {
			"position":	[10, 2, 5],
			"yr":	0,
			"index":	64
		}, {
			"position":	[11, 2, 5],
			"yr":	0.25,
			"index":	43
		}, {
			"position":	[1, 0, 6],
			"yr":	0.5,
			"index":	77
		}, {
			"position":	[2, 0, 6],
			"yr":	0.5,
			"index":	43
		}, {
			"position":	[3, 0, 6],
			"yr":	0.5,
			"index":	43
		}, {
			"position":	[4, 0, 6],
			"yr":	0.5,
			"index":	43
		}, {
			"position":	[5, 0, 6],
			"yr":	0.25,
			"index":	77
		}, {
			"position":	[9, 2, 6],
			"yr":	0.75,
			"index":	77
		}, {
			"position":	[10, 2, 6],
			"yr":	0,
			"index":	43
		}, {
			"position":	[11, 2, 6],
			"yr":	0,
			"index":	77
		}, {
			"position":	[1, 0, 7],
			"yr":	0.75,
			"index":	43
		}, {
			"position":	[2, 0, 7],
			"yr":	0,
			"index":	37
		}, {
			"position":	[3, 0, 7],
			"yr":	0,
			"index":	37
		}, {
			"position":	[4, 0, 7],
			"yr":	0,
			"index":	37
		}, {
			"position":	[5, 0, 7],
			"yr":	0.25,
			"index":	43
		}, {
			"position":	[6, 1, 7],
			"yr":	0.5,
			"index":	77
		}, {
			"position":	[7, 1, 7],
			"yr":	0.5,
			"index":	43
		}, {
			"position":	[8, 1, 7],
			"yr":	0.25,
			"index":	77
		}, {
			"position":	[9, 2, 7],
			"yr":	0.5,
			"index":	77
		}, {
			"position":	[10, 2, 7],
			"yr":	0.5,
			"index":	43
		}, {
			"position":	[11, 2, 7],
			"yr":	0.25,
			"index":	77
		}, {
			"position":	[1, 0, 8],
			"yr":	0.75,
			"index":	43
		}, {
			"position":	[2, 0, 8],
			"yr":	0,
			"index":	37
		}, {
			"position":	[3, 0, 8],
			"yr":	0.25,
			"index":	54
		}, {
			"position":	[4, 0, 8],
			"yr":	0.25,
			"index":	37
		}, {
			"position":	[5, 0, 8],
			"yr":	0.25,
			"index":	43
		}, {
			"position":	[6, 1, 8],
			"yr":	0.75,
			"index":	43
		}, {
			"position":	[7, 1, 8],
			"yr":	0,
			"index":	64
		}, {
			"position":	[8, 1, 8],
			"yr":	0.25,
			"index":	43
		}, {
			"position":	[9, 2, 8],
			"yr":	0.75,
			"index":	43
		}, {
			"position":	[10, 2, 8],
			"yr":	0,
			"index":	64
		}, {
			"position":	[11, 2, 8],
			"yr":	0.25,
			"index":	43
		}, {
			"position":	[1, 0, 9],
			"yr":	0.75,
			"index":	43
		}, {
			"position":	[2, 0, 9],
			"yr":	0,
			"index":	37
		}, {
			"position":	[3, 0, 9],
			"yr":	0,
			"index":	37
		}, {
			"position":	[4, 0, 9],
			"yr":	0.25,
			"index":	37
		}, {
			"position":	[5, 0, 9],
			"yr":	0.25,
			"index":	43
		}, {
			"position":	[6, 1, 9],
			"yr":	0.75,
			"index":	77
		}, {
			"position":	[7, 1, 9],
			"yr":	0,
			"index":	43
		}, {
			"position":	[8, 1, 9],
			"yr":	0,
			"index":	77
		}, {
			"position":	[9, 2, 9],
			"yr":	0.75,
			"index":	77
		}, {
			"position":	[10, 2, 9],
			"yr":	0,
			"index":	43
		}, {
			"position":	[11, 2, 9],
			"yr":	0,
			"index":	77
		}, {
			"position":	[1, 0, 10],
			"yr":	0.75,
			"index":	77
		}, {
			"position":	[2, 0, 10],
			"yr":	0,
			"index":	43
		}, {
			"position":	[3, 0, 10],
			"yr":	0,
			"index":	43
		}, {
			"position":	[4, 0, 10],
			"yr":	0,
			"index":	43
		}, {
			"position":	[5, 0, 10],
			"yr":	0,
			"index":	77
		}],
	"strats":	[{
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[47.199951171875, 0, 119.099853515625],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[52.7998046875, 0, 122.059814453125],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[54.639892578125, 0, 127.81982421875],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[52.639892578125, 0, 133.659912109375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[47.679931640625, 0, 136.4599609375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[42.719970703125, 0, 134.77978515625],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[40.47998046875, 0, 129.39990234375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[41.83984375, 0, 121.97998046875],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[116, 1.599853515625, 128.5],
			"rotation":	[0, 0, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[98304, 2949120, 0, 0, 0, 0, 0, 0],
			"position":	[110, 0, 129],
			"rotation":	[0, 0.749267578125, 0],
			"name":	"DantiniZap",
			"waypoints":	[{
					"position":	[110, 0, 130],
					"var":	0
				}]
		}, {
			"params":	[0, 65536, 0, 0, 131072, 0, 196608, 0],
			"position":	[80.39990234375, 0, 129],
			"rotation":	[0, 0.249755859375, 0],
			"name":	"PlatformNormal",
			"waypoints":	[{
					"position":	[80.47998046875, 0, 128.81982421875],
					"var":	65536
				}, {
					"position":	[97.039794921875, 1.599853515625, 128.5],
					"var":	65536
				}]
		}, {
			"params":	[0, 65536, 0, 0, 131072, 0, 196608, 0],
			"position":	[126, 1.759765625, 128.5],
			"rotation":	[0, 0.249755859375, 0],
			"name":	"PlatformNormal",
			"waypoints":	[{
					"position":	[126, 1.759765625, 128.47998046875],
					"var":	65536
				}, {
					"position":	[144, 3.199951171875, 128.2998046875],
					"var":	65536
				}]
		}, {
			"params":	[196608, 0, 0, 0, 0, 0, 0, 0],
			"position":	[165.27978515625, 3.999755859375, 129.5],
			"rotation":	[0, 0, 0],
			"name":	"SmashBlockBonus",
			"waypoints":	[]
		}, {
			"params":	[98304, 2949120, 0, 0, 0, 0, 0, 0],
			"position":	[156, 4.639892578125, 129],
			"rotation":	[0, 0.749267578125, 0],
			"name":	"DantiniZap",
			"waypoints":	[{
					"position":	[156, 4.639892578125, 129],
					"var":	0
				}]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[160, 16.31982421875, 119.2998046875],
			"rotation":	[0, 0, 0],
			"name":	"ForestMonkBarEnd",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[160, 16.31982421875, 110.419921875],
			"rotation":	[0, 0, 0],
			"name":	"ForestMonkBarStr",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[160, 16.31982421875, 98.539794921875],
			"rotation":	[0, 0, 0],
			"name":	"ForestMonkBarStr",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[160, 16.31982421875, 89.639892578125],
			"rotation":	[0, 0.49951171875, 0],
			"name":	"ForestMonkBarEnd",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[160, 4.47998046875, 77.5],
			"rotation":	[0, 0, 0],
			"name":	"Spring",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[159.119873046875, 3.679931640625, 33],
			"rotation":	[0, 0, 0],
			"name":	"Spring",
			"waypoints":	[]
		}, {
			"params":	[65536, 0, 0, 0, 0, 0, 0, 0],
			"position":	[159.679931640625, 1.43994140625, 56],
			"rotation":	[0, 0, 0],
			"name":	"PlatformCrumble",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[159.199951171875, 22.079833984375, 32.85986328125],
			"rotation":	[0, 0, 0],
			"name":	"KeyForLockedDoorFloat",
			"waypoints":	[]
		}],
	"doors":	[{
			"position":	[3, 0, 8],
			"level":	36,
			"sublevel":	3,
			"flags":	["floor", "start"],
			"id":	0
		}],
	"point_lights":	[],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[72, 72, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 128]
		}, {
			"position":	[0, 0.5, -0.000244140625],
			"colour":	[56, 56, 48]
		}],
	"ambient_colour":	[144, 144, 128]
}
