=== vs49688/CrocUtils/resources/map.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
	"mapstring": {
	  "type": "string",
	  "maxLength": 255
	},
	"uint16": {
	  "type": "integer",
	  "minimum": 0,
	  "maximum": 65535
	},
	"uint32": {
	  "type": "integer",
	  "minimum": 0,
	  "maximum": 4294967295
	},
	"vector3": {
	  "type": "array",
	  "minLength": 3,
	  "maxLength": 3,
	  "items": {
		"type": "number"
	  }
	},
	"colour": {
	  "type": "array",
	  "minLength": 3,
	  "maxLength": 3,
	  "items": {
		"type": "integer",
		"minimum": 0,
		"maximum": 255
	  }
	},
	"track": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"yr": {
		  "type": "number"
		},
		"index": {
		  "$ref": "#/definitions/uint16"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"yr",
		"index"
	  ]
	},
	"waypoint": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"var": {
		  "$ref": "#/definitions/uint32"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"var"
	  ]
	},
	"strategy": {
	  "type": "object",
	  "properties": {
		"params": {
		  "type": "array",
		  "minLength": 8,
		  "maxLength": 8,
		  "items": {
			"$ref": "#/definitions/uint32"
		  }
		},
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"rotation": {
		  "$ref": "#/definitions/vector3"
		},
		"name": {
		  "type": "string",
		  "minLength": 1,
		  "maxLength": 255
		},
		"waypoints": {
		  "type": "array",
		  "items": {
			"$ref": "#/definitions/waypoint"
		  }
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"params",
		"position",
		"rotation",
		"name",
		"waypoints"
	  ]
	},
	"door": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"level": {
		  "$ref": "#/definitions/uint16"
		},
		"sublevel": {
		  "$ref": "#/definitions/uint16"
		},
		"flags": {
		  "type": "array",
		  "items": {
			"enum": [
			  "normal",
			  "floor",
			  "ceiling",
			  "start",
			  "final"
			]
		  },
		  "uniqueItems": true
		},
		"id": {
		  "$ref": "#/definitions/uint16"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"level",
		"sublevel",
		"flags",
		"id"
	  ]
	},
	"point_light": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"colour": {
		  "$ref": "#/definitions/colour"
		},
		"fade_from": {
		  "type": "number"
		},
		"fade_to": {
		  "type": "number"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"colour",
		"fade_from",
		"fade_to"
	  ]
	},
	"direct_light": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"colour": {
		  "$ref": "#/definitions/colour"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"colour"
	  ]
	}
  },
  "type": "object",
  "properties": {
	"_meta": {
	  "type": "object",
	  "properties": {
		"version": {
		  "type": "integer"
		},
		"format": {
		  "enum": [
			"normal",
			"v12",
			"v12_old",
			"v12_old_noambient"
		  ]
		},
		"level": {
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 999
		},
		"sublevel": {
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 99
		},
		"checksum": {
		  "type": "integer"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"version",
		"format",
		"level",
		"sublevel",
		"checksum"
	  ]
	},
	"path": {
	  "$ref": "#/definitions/mapstring"
	},
	"name": {
	  "$ref": "#/definitions/mapstring"
	},
	"width": {
	  "$ref": "#/definitions/uint16"
	},
	"height": {
	  "$ref": "#/definitions/uint16"
	},
	"depth": {
	  "$ref": "#/definitions/uint16"
	},
	"style": {
	  "oneOf": [
		{
		  "enum": [
			"ice",
			"water",
			"castle",
			"desert",
			"cave",
			"wood",
			"dungeon",
			"boss1",
			"boss2",
			"boss3",
			"boss4",
			"boss5",
			"boss6",
			"boss7",
			"boss8",
			"boss9",
			"island1",
			"island2",
			"island3",
			"island4",
			"island5",
			"iceslide",
			"boulder",
			"icecave"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 24
		}
	  ]
	},
	"flags": {
	  "$ref": "#/definitions/uint32"
	},
	"cd_track": {
	  "$ref": "#/definitions/uint32"
	},
	"background": {
	  "$ref": "#/definitions/uint32"
	},
	"effect": {
	  "oneOf": [
		{
		  "enum": [
			"none",
			"snow",
			"fog",
			"torch",
			"torch_lightning",
			"torch_big",
			"torch_big_lightning",
			"dark",
			"snow_small",
			"snow_island",
			"torch_giant"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 15
		}
	  ]
	},
	"wait": {
	  "$ref": "#/definitions/uint32"
	},
	"ambience": {
	  "oneOf": [
		{
		  "enum": [
			"none",
			"bird",
			"drip",
			"nght",
			"watr",
			"crwd",
			"lava",
			"tunl",
			"ice1",
			"tomb",
			"des1",
			"dcav",
			"slde",
			"cast",
			"dngn",
			"ice2",
			"clwd",
			"whal",
			"moat",
			"dusk",
			"wind",
			"cica",
			"dant"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 22
		}
	  ]
	},
	"start_rotation": {
	  "type": "number"
	},
	"tracks": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/track"
	  }
	},
	"strats": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/strategy"
	  }
	},
	"doors": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/door"
	  }
	},
	"point_lights": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/point_light"
	  }
	},
	"direct_lights": {
	  "type": "array",
	  "minItems": 3,
	  "maxItems": 3,
	  "items": {
		"$ref": "#/definitions/direct_light"
	  }
	},
	"ambient_colour": {
	  "$ref": "#/definitions/colour"
	},
	"$schema": {
	  "type": "string"
	}
  },
  "additionalProperties": false,
  "required": [
	"path",
	"name",
	"width",
	"height",
	"depth",
	"style",
	"flags",
	"cd_track",
	"background",
	"effect",
	"wait",
	"ambience",
	"start_rotation",
	"tracks",
	"strats",
	"doors",
	"point_lights",
	"direct_lights",
	"ambient_colour"
  ]
}

=== vs49688/CrocUtils/resources/maps/json/beta012/MP013_02.json
{
	"_meta":	{
		"version":	12,
		"format":	"v12_old",
		"level":	13,
		"sublevel":	2,
		"checksum":	0
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\ISLAND1\\LEVEL4\\MAP3.MAP",
	"name":	"All Together Now",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"wood",
	"flags":	8,
	"cd_track":	23,
	"background":	16,
	"effect":	"none",
	"wait":	0,
	"ambience":	"nght",
	"start_rotation":	0.49951171875,
	"tracks":	[{
			"position":	[2, 0, 3],
			"yr":	0.25,
			"index":	98
		}, {
			"position":	[3, 0, 3],
			"yr":	0,
			"index":	95
		}, {
			"position":	[4, 0, 3],
			"yr":	0,
			"index":	95
		}, {
			"position":	[5, 0, 3],
			"yr":	0,
			"index":	98
		}, {
			"position":	[0, 0, 4],
			"yr":	0.75,
			"index":	48
		}, {
			"position":	[2, 0, 4],
			"yr":	0.25,
			"index":	25
		}, {
			"position":	[3, 0, 4],
			"yr":	0.5,
			"index":	24
		}, {
			"position":	[4, 0, 4],
			"yr":	0.25,
			"index":	24
		}, {
			"position":	[5, 0, 4],
			"yr":	0.75,
			"index":	26
		}, {
			"position":	[7, 0, 4],
			"yr":	0.25,
			"index":	48
		}, {
			"position":	[0, 0, 5],
			"yr":	0.75,
			"index":	50
		}, {
			"position":	[2, 0, 5],
			"yr":	0.5,
			"index":	3
		}, {
			"position":	[3, 0, 5],
			"yr":	0,
			"index":	0
		}, {
			"position":	[4, 0, 5],
			"yr":	0.5,
			"index":	61
		}, {
			"position":	[5, 0, 5],
			"yr":	0.75,
			"index":	3
		}, {
			"position":	[7, 0, 5],
			"yr":	0.25,
			"index":	50
		}, {
			"position":	[1, 0, 6],
			"yr":	0,
			"index":	55
		}, {
			"position":	[3, 0, 6],
			"yr":	0.5,
			"index":	79
		}, {
			"position":	[6, 0, 6],
			"yr":	0.25,
			"index":	55
		}, {
			"position":	[2, 0, 7],
			"yr":	0,
			"index":	50
		}, {
			"position":	[3, 0, 7],
			"yr":	0,
			"index":	50
		}, {
			"position":	[4, 0, 7],
			"yr":	0,
			"index":	50
		}, {
			"position":	[5, 0, 7],
			"yr":	0,
			"index":	50
		}, {
			"position":	[2, 8, 0],
			"yr":	0.75,
			"index":	56
		}, {
			"position":	[5, 8, 0],
			"yr":	0.5,
			"index":	56
		}, {
			"position":	[1, 8, 1],
			"yr":	0.75,
			"index":	55
		}, {
			"position":	[6, 8, 1],
			"yr":	0.5,
			"index":	55
		}, {
			"position":	[0, 8, 2],
			"yr":	0.75,
			"index":	50
		}, {
			"position":	[7, 8, 2],
			"yr":	0.25,
			"index":	50
		}, {
			"position":	[0, 8, 3],
			"yr":	0.75,
			"index":	50
		}, {
			"position":	[2, 8, 3],
			"yr":	0.25,
			"index":	55
		}, {
			"position":	[3, 8, 3],
			"yr":	0,
			"index":	50
		}, {
			"position":	[4, 8, 3],
			"yr":	0,
			"index":	50
		}, {
			"position":	[5, 8, 3],
			"yr":	0,
			"index":	55
		}, {
			"position":	[7, 8, 3],
			"yr":	0.25,
			"index":	50
		}, {
			"position":	[0, 8, 4],
			"yr":	0.75,
			"index":	50
		}, {
			"position":	[1, 8, 4],
			"yr":	0.25,
			"index":	3
		}, {
			"position":	[6, 8, 4],
			"yr":	0,
			"index":	3
		}, {
			"position":	[7, 8, 4],
			"yr":	0.25,
			"index":	50
		}, {
			"position":	[1, 8, 5],
			"yr":	0,
			"index":	0
		}, {
			"position":	[6, 8, 5],
			"yr":	0,
			"index":	0
		}, {
			"position":	[2, 8, 6],
			"yr":	0.25,
			"index":	40
		}, {
			"position":	[3, 8, 6],
			"yr":	0.75,
			"index":	35
		}, {
			"position":	[4, 8, 6],
			"yr":	0.75,
			"index":	35
		}, {
			"position":	[5, 8, 6],
			"yr":	0.75,
			"index":	40
		}, {
			"position":	[2, 16, 0],
			"yr":	0.75,
			"index":	55
		}, {
			"position":	[3, 16, 0],
			"yr":	0,
			"index":	64
		}, {
			"position":	[4, 16, 0],
			"yr":	0,
			"index":	64
		}, {
			"position":	[5, 16, 0],
			"yr":	0.5,
			"index":	55
		}, {
			"position":	[2, 16, 1],
			"yr":	0,
			"index":	3
		}, {
			"position":	[3, 16, 1],
			"yr":	0,
			"index":	92
		}, {
			"position":	[5, 16, 1],
			"yr":	0.25,
			"index":	3
		}, {
			"position":	[1, 16, 2],
			"yr":	0,
			"index":	36
		}, {
			"position":	[2, 16, 2],
			"yr":	0.75,
			"index":	40
		}, {
			"position":	[3, 16, 2],
			"yr":	0,
			"index":	91
		}, {
			"position":	[4, 16, 2],
			"yr":	0,
			"index":	61
		}, {
			"position":	[5, 16, 2],
			"yr":	0.25,
			"index":	40
		}, {
			"position":	[6, 16, 2],
			"yr":	0.75,
			"index":	36
		}, {
			"position":	[1, 16, 3],
			"yr":	0.5,
			"index":	40
		}, {
			"position":	[6, 16, 3],
			"yr":	0.5,
			"index":	40
		}, {
			"position":	[3, 24, 0],
			"yr":	0,
			"index":	23
		}, {
			"position":	[4, 24, 0],
			"yr":	0.75,
			"index":	23
		}, {
			"position":	[3, 24, 1],
			"yr":	0.25,
			"index":	23
		}, {
			"position":	[4, 24, 1],
			"yr":	0.5,
			"index":	24
		}],
	"strats":	[{
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.868743896484375, 0.9666595458984375, 5.15625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.90625, 1.0749969482421875, 4.46875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.3562469482421875, 1.2166595458984375, 4.33123779296875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.7562408447265625, 1.3749847412109375, 4.0437469482421875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.2562408447265625, 1.524993896484375, 3.8499908447265625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.7199859619140625, 1.683319091796875, 3.738739013671875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.4974822998046875, 2.89166259765625, 0.4774932861328125],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[983040, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.3249969482421875, 1.3499908447265625, 4.29998779296875],
			"rotation":	[0, 0, 0],
			"name":	"Jumpy",
			"waypoints":	[{
					"position":	[3.3549957275390625, 1.3499908447265625, 4.319976806640625],
					"var":	0
				}]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.2549896240234375, 1.649993896484375, 3.8399810791015625],
			"rotation":	[0, 0, 0],
			"name":	"Jumpy",
			"waypoints":	[{
					"position":	[4.2537384033203125, 1.649993896484375, 3.8599700927734375],
					"var":	0
				}]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.8762359619140625, 1.0833282470703125, 5.125],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.899993896484375, 1.1999969482421875, 4.467498779296875],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.7549896240234375, 1.5, 4.0437469482421875],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.6987457275390625, 1.8333282470703125, 3.74749755859375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3, 0, 5.6962432861328125],
			"rotation":	[0, 0.49951171875, 0],
			"name":	"NormalDoor",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[6.199981689453125, 2, 3.9375],
			"rotation":	[0, 0.49951171875, 0],
			"name":	"SmashBlockGobbo",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.489990234375, 3.25, 0.46875],
			"rotation":	[0, 0, 0],
			"name":	"Letter_S",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3, 2, 1.4375],
			"rotation":	[0, 0, 0],
			"name":	"BonusDoor",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[1, 2, 2.96875],
			"rotation":	[0, 0.49951171875, 0],
			"name":	"FinalExit",
			"waypoints":	[]
		}, {
			"params":	[65536, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.375, 0, 3.5625],
			"rotation":	[0, 0, 0],
			"name":	"LavaBlubs",
			"waypoints":	[{
					"position":	[4.125, 0, 3.40625],
					"var":	0
				}, {
					"position":	[2.75, 0, 3.40625],
					"var":	0
				}, {
					"position":	[2, 0, 3.84375],
					"var":	0
				}, {
					"position":	[5.125, 0, 3.84375],
					"var":	0
				}]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[1, 1, 5],
			"rotation":	[0, 0, 0],
			"name":	"SmashBlockGobbo",
			"waypoints":	[]
		}],
	"doors":	[{
			"position":	[3, 0, 5],
			"level":	0,
			"sublevel":	0,
			"flags":	["start"],
			"id":	0
		}, {
			"position":	[3, 0, 6],
			"level":	13,
			"sublevel":	1,
			"flags":	["normal"],
			"id":	0
		}, {
			"position":	[3, 2, 1],
			"level":	13,
			"sublevel":	4,
			"flags":	["normal"],
			"id":	0
		}],
	"point_lights":	[{
			"position":	[3.875, 0.5833282470703125, 5],
			"colour":	[83, 143, 151],
			"fade_from":	0.001953125,
			"fade_to":	0.01171875
		}],
	"direct_lights":	[{
			"position":	[0, 0.00390625, 0],
			"colour":	[64, 64, 0]
		}, {
			"position":	[0, -2.310546875, 0.003173828125],
			"colour":	[255, 128, 0]
		}, {
			"position":	[0, -0.060546875, 0.062255859375],
			"colour":	[43, 43, 0]
		}],
	"ambient_colour":	[55, 55, 0]
}

=== vs49688/CrocUtils/resources/maps/json/beta012/MP042_05.json
{
	"_meta":	{
		"version":	12,
		"format":	"v12_old",
		"level":	42,
		"sublevel":	5,
		"checksum":	0
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\ISLAND4\\LEVEL3\\MAP6.MAP",
	"name":	"Chasm Clincher",
	"width":	12,
	"height":	14,
	"depth":	2,
	"style":	"cave",
	"flags":	0,
	"cd_track":	0,
	"background":	0,
	"effect":	6,
	"wait":	0,
	"ambience":	"none",
	"start_rotation":	-0.045654296875,
	"tracks":	[{
			"position":	[9, 0, 4],
			"yr":	0,
			"index":	56
		}, {
			"position":	[7, 0, 5],
			"yr":	0.5,
			"index":	15
		}, {
			"position":	[8, 0, 5],
			"yr":	0.25,
			"index":	12
		}, {
			"position":	[9, 0, 5],
			"yr":	0.25,
			"index":	47
		}, {
			"position":	[10, 0, 5],
			"yr":	0.25,
			"index":	15
		}, {
			"position":	[4, 0, 6],
			"yr":	0,
			"index":	56
		}, {
			"position":	[7, 0, 6],
			"yr":	0.5,
			"index":	12
		}, {
			"position":	[8, 0, 6],
			"yr":	0,
			"index":	3
		}, {
			"position":	[9, 0, 6],
			"yr":	0.75,
			"index":	12
		}, {
			"position":	[10, 0, 6],
			"yr":	0,
			"index":	15
		}, {
			"position":	[1, 0, 7],
			"yr":	0.5,
			"index":	25
		}, {
			"position":	[2, 0, 7],
			"yr":	0.25,
			"index":	10
		}, {
			"position":	[3, 0, 7],
			"yr":	0.25,
			"index":	7
		}, {
			"position":	[4, 0, 7],
			"yr":	0.25,
			"index":	47
		}, {
			"position":	[5, 0, 7],
			"yr":	0.25,
			"index":	15
		}, {
			"position":	[7, 0, 7],
			"yr":	0.5,
			"index":	7
		}, {
			"position":	[8, 0, 7],
			"yr":	0,
			"index":	9
		}, {
			"position":	[1, 0, 8],
			"yr":	0.5,
			"index":	10
		}, {
			"position":	[2, 0, 8],
			"yr":	0,
			"index":	32
		}, {
			"position":	[3, 0, 8],
			"yr":	0.75,
			"index":	9
		}, {
			"position":	[4, 0, 8],
			"yr":	0.75,
			"index":	14
		}, {
			"position":	[5, 0, 8],
			"yr":	0,
			"index":	15
		}, {
			"position":	[7, 0, 8],
			"yr":	0.5,
			"index":	10
		}, {
			"position":	[8, 0, 8],
			"yr":	0,
			"index":	10
		}, {
			"position":	[1, 0, 9],
			"yr":	0.5,
			"index":	10
		}, {
			"position":	[2, 0, 9],
			"yr":	0,
			"index":	10
		}, {
			"position":	[6, 0, 9],
			"yr":	0.5,
			"index":	25
		}, {
			"position":	[7, 0, 9],
			"yr":	0.5,
			"index":	32
		}, {
			"position":	[8, 0, 9],
			"yr":	0,
			"index":	10
		}, {
			"position":	[1, 0, 10],
			"yr":	0.5,
			"index":	10
		}, {
			"position":	[2, 0, 10],
			"yr":	0.25,
			"index":	32
		}, {
			"position":	[3, 0, 10],
			"yr":	0.25,
			"index":	7
		}, {
			"position":	[4, 0, 10],
			"yr":	0.25,
			"index":	12
		}, {
			"position":	[5, 0, 10],
			"yr":	0.25,
			"index":	9
		}, {
			"position":	[6, 0, 10],
			"yr":	0.5,
			"index":	32
		}, {
			"position":	[7, 0, 10],
			"yr":	0.75,
			"index":	22
		}, {
			"position":	[8, 0, 10],
			"yr":	0,
			"index":	10
		}, {
			"position":	[1, 0, 11],
			"yr":	0.75,
			"index":	25
		}, {
			"position":	[2, 0, 11],
			"yr":	0.75,
			"index":	10
		}, {
			"position":	[3, 0, 11],
			"yr":	0.75,
			"index":	9
		}, {
			"position":	[4, 0, 11],
			"yr":	0.75,
			"index":	12
		}, {
			"position":	[5, 0, 11],
			"yr":	0.75,
			"index":	7
		}, {
			"position":	[6, 0, 11],
			"yr":	0.75,
			"index":	10
		}, {
			"position":	[7, 0, 11],
			"yr":	0.75,
			"index":	10
		}, {
			"position":	[8, 0, 11],
			"yr":	0,
			"index":	25
		}],
	"strats":	[{
			"params":	[32768, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.3512420654296875, 0, 10.499984741210938],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[1966080, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.5424957275390625, 0, 7.4787445068359375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[26214, 0, 0, 0, 0, 0, 0, 0],
			"position":	[1.5, 0, 8.989990234375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[26214, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.488739013671875, 0, 10.40625],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.553741455078125, 0, 7.4799957275390625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[1.5, 0, 9],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.4787445068359375, 0, 10.40625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[8.99749755859375, 0, 4.53125],
			"rotation":	[0, 0, 0],
			"name":	"FinalExit",
			"waypoints":	[]
		}, {
			"params":	[983040, 19660, 983040, 0, 0, 0, 0, 0],
			"position":	[5.5, 0, 10.53125],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDip",
			"waypoints":	[]
		}, {
			"params":	[983040, 19660, 983040, 0, 0, 0, 0, 0],
			"position":	[6.5, 0, 10.5],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDip",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[7.5, 0, 9.8125],
			"rotation":	[0, 0, 0],
			"name":	"PlatformStepStone",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[7.5, 0, 9.04374694824219],
			"rotation":	[0, 0, 0],
			"name":	"PlatformStepStone",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[7.5, 0, 10.53125],
			"rotation":	[0, 0, 0],
			"name":	"PlatformCrumble",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[7.5, 0, 7.29998779296875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[7.5, 0, 8.20623779296875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformStepStone",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.5, 0, 7.5],
			"rotation":	[0, 0.916015625, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4, 0, 10.53125],
			"rotation":	[0, 0.124755859375, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[7.5, 0, 5.53125],
			"rotation":	[0, 0.055419921875, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[1.819976806640625, 0, 8.1099853515625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformStepStone",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[1.75, 0, 9.92498779296875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformStepStone",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4, 0, 6.4487457275390625],
			"rotation":	[0, 0, 0],
			"name":	"NormalDoor",
			"waypoints":	[]
		}],
	"doors":	[{
			"position":	[9, 0, 4],
			"level":	44,
			"sublevel":	0,
			"flags":	["final"],
			"id":	0
		}, {
			"position":	[4, 0, 6],
			"level":	42,
			"sublevel":	4,
			"flags":	["normal"],
			"id":	0
		}, {
			"position":	[4, 0, 7],
			"level":	0,
			"sublevel":	0,
			"flags":	["start"],
			"id":	0
		}],
	"point_lights":	[],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[64, 64, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 128]
		}, {
			"position":	[0, 0.5, -0.000244140625],
			"colour":	[43, 43, 43]
		}],
	"ambient_colour":	[64, 64, 64]
}

=== vs49688/CrocUtils/resources/maps/json/slus00530/MP083_03.json
{
	"_meta":	{
		"version":	20,
		"format":	"normal",
		"level":	83,
		"sublevel":	3,
		"checksum":	9061
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\INTROS\\OUTRO\\JIG4.MAP",
	"name":	"Default New Map",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"castle",
	"flags":	0,
	"cd_track":	0,
	"background":	24,
	"effect":	"none",
	"wait":	0,
	"ambience":	"none",
	"start_rotation":	0.49951171875,
	"tracks":	[],
	"strats":	[{
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[64, 5.97314453125, 32.999755859375],
			"rotation":	[0, 0, 0],
			"name":	"IntroStart",
			"waypoints":	[]
		}],
	"doors":	[],
	"point_lights":	[],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[64, 64, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 104]
		}, {
			"position":	[0, 0.5, -0.000244140625],
			"colour":	[48, 48, 48]
		}],
	"ambient_colour":	[64, 64, 64]
}

=== vs49688/CrocUtils/resources/maps/json/pc/MP039_04.json
{
	"_meta":	{
		"version":	20,
		"format":	"normal",
		"level":	39,
		"sublevel":	4,
		"checksum":	24683
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\DESERT\\BONUS2\\MAP5.MAP",
	"name":	"Default New Map",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"desert",
	"flags":	0,
	"cd_track":	42,
	"background":	25,
	"effect":	"none",
	"wait":	0,
	"ambience":	"cica",
	"start_rotation":	0.011962890625,
	"tracks":	[{
			"position":	[2, 0, 1],
			"yr":	0,
			"index":	26
		}, {
			"position":	[6, 0, 10],
			"yr":	0,
			"index":	27
		}, {
			"position":	[2, 8, 1],
			"yr":	0,
			"index":	27
		}, {
			"position":	[2, 8, 6],
			"yr":	0.75,
			"index":	47
		}, {
			"position":	[4, 8, 8],
			"yr":	0.25,
			"index":	47
		}, {
			"position":	[6, 8, 10],
			"yr":	0,
			"index":	54
		}, {
			"position":	[2, 16, 1],
			"yr":	0,
			"index":	54
		}, {
			"position":	[2, 16, 4],
			"yr":	0.25,
			"index":	47
		}, {
			"position":	[0, 16, 6],
			"yr":	0.5,
			"index":	47
		}, {
			"position":	[4, 16, 6],
			"yr":	0,
			"index":	47
		}, {
			"position":	[2, 16, 8],
			"yr":	0.75,
			"index":	47
		}],
	"strats":	[{
			"params":	[0, 65536, 0, 65536, 131072, 0, 0, 0],
			"position":	[2, 1.899993896484375, 1.774993896484375],
			"rotation":	[0, 0, 0],
			"name":	"PlatformNormal",
			"waypoints":	[{
					"position":	[2, 1.899993896484375, 1.774993896484375],
					"var":	65536
				}, {
					"position":	[2, 1.899993896484375, 3],
					"var":	65536
				}]
		}, {
			"params":	[0, 0, 0, 983040, 65536, 0, 0, 0],
			"position":	[2, 1.8999786376953125, 6.0012359619140625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 983040, 65536, 0, 0, 0],
			"position":	[2, 1.8999786376953125, 6],
			"rotation":	[0, 0.666015625, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 983040, 65536, 0, 0, 0],
			"position":	[2, 1.79998779296875, 6],
			"rotation":	[0, 0.3330078125, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4, 2, 6.0024871826171875],
			"rotation":	[0, 0, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2, 2, 8.00248718261719],
			"rotation":	[0, 0, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[0, 2, 6.0024871826171875],
			"rotation":	[0, 0, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2, 3, 6.0012359619140625],
			"rotation":	[0, 0, 0],
			"name":	"SmashBlock",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3, 0.899993896484375, 7.0012359619140625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[5, 0.899993896484375, 9],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}],
	"doors":	[{
			"position":	[6, 1, 10],
			"level":	39,
			"sublevel":	1,
			"flags":	["floor"],
			"id":	0
		}, {
			"position":	[2, 2, 1],
			"level":	39,
			"sublevel":	3,
			"flags":	["floor", "start"],
			"id":	0
		}],
	"point_lights":	[],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[72, 72, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 128]
		}, {
			"position":	[0, 0.5, -0.000244140625],
			"colour":	[56, 56, 48]
		}],
	"ambient_colour":	[144, 144, 128]
}

=== vs49688/CrocUtils/resources/maps/json/slps01055/MP084_03.json
{
	"_meta":	{
		"version":	12,
		"format":	"normal",
		"level":	0,
		"sublevel":	3,
		"checksum":	9708
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\INTROS\\OUTRO\\GAMEO4.MAP",
	"name":	"Default New Map",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"castle",
	"flags":	0,
	"cd_track":	0,
	"background":	11,
	"effect":	"none",
	"wait":	0,
	"ambience":	"none",
	"start_rotation":	0.49951171875,
	"tracks":	[{
			"position":	[1, 0, 0],
			"yr":	0.5,
			"index":	40
		}, {
			"position":	[2, 0, 0],
			"yr":	0.5,
			"index":	40
		}, {
			"position":	[3, 0, 0],
			"yr":	0.5,
			"index":	40
		}, {
			"position":	[4, 0, 0],
			"yr":	0.5,
			"index":	40
		}, {
			"position":	[5, 0, 0],
			"yr":	0.5,
			"index":	40
		}, {
			"position":	[0, 0, 1],
			"yr":	0.75,
			"index":	40
		}, {
			"position":	[6, 0, 1],
			"yr":	0.25,
			"index":	40
		}, {
			"position":	[1, 0, 2],
			"yr":	0,
			"index":	40
		}, {
			"position":	[2, 0, 2],
			"yr":	0,
			"index":	40
		}, {
			"position":	[3, 0, 2],
			"yr":	0,
			"index":	40
		}, {
			"position":	[4, 0, 2],
			"yr":	0,
			"index":	40
		}, {
			"position":	[5, 0, 2],
			"yr":	0,
			"index":	40
		}, {
			"position":	[1, 8, 1],
			"yr":	0,
			"index":	0
		}, {
			"position":	[2, 8, 1],
			"yr":	0,
			"index":	0
		}, {
			"position":	[3, 8, 1],
			"yr":	0,
			"index":	0
		}, {
			"position":	[4, 8, 1],
			"yr":	0,
			"index":	0
		}, {
			"position":	[5, 8, 1],
			"yr":	0,
			"index":	0
		}],
	"strats":	[{
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[48.5, 16, 18.599853515625],
			"rotation":	[0, 0.749267578125, 0],
			"name":	"IntroStart",
			"waypoints":	[]
		}],
	"doors":	[],
	"point_lights":	[],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[64, 64, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 104]
		}, {
			"position":	[0, 0.5, -0.000244140625],
			"colour":	[48, 48, 48]
		}],
	"ambient_colour":	[64, 64, 64]
}
