=== vs49688/CrocUtils/resources/map.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
	"mapstring": {
	  "type": "string",
	  "maxLength": 255
	},
	"uint16": {
	  "type": "integer",
	  "minimum": 0,
	  "maximum": 65535
	},
	"uint32": {
	  "type": "integer",
	  "minimum": 0,
	  "maximum": 4294967295
	},
	"vector3": {
	  "type": "array",
	  "minLength": 3,
	  "maxLength": 3,
	  "items": {
		"type": "number"
	  }
	},
	"colour": {
	  "type": "array",
	  "minLength": 3,
	  "maxLength": 3,
	  "items": {
		"type": "integer",
		"minimum": 0,
		"maximum": 255
	  }
	},
	"track": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"yr": {
		  "type": "number"
		},
		"index": {
		  "$ref": "#/definitions/uint16"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"yr",
		"index"
	  ]
	},
	"waypoint": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"var": {
		  "$ref": "#/definitions/uint32"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"var"
	  ]
	},
	"strategy": {
	  "type": "object",
	  "properties": {
		"params": {
		  "type": "array",
		  "minLength": 8,
		  "maxLength": 8,
		  "items": {
			"$ref": "#/definitions/uint32"
		  }
		},
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"rotation": {
		  "$ref": "#/definitions/vector3"
		},
		"name": {
		  "type": "string",
		  "minLength": 1,
		  "maxLength": 255
		},
		"waypoints": {
		  "type": "array",
		  "items": {
			"$ref": "#/definitions/waypoint"
		  }
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"params",
		"position",
		"rotation",
		"name",
		"waypoints"
	  ]
	},
	"door": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"level": {
		  "$ref": "#/definitions/uint16"
		},
		"sublevel": {
		  "$ref": "#/definitions/uint16"
		},
		"flags": {
		  "type": "array",
		  "items": {
			"enum": [
			  "normal",
			  "floor",
			  "ceiling",
			  "start",
			  "final"
			]
		  },
		  "uniqueItems": true
		},
		"id": {
		  "$ref": "#/definitions/uint16"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"level",
		"sublevel",
		"flags",
		"id"
	  ]
	},
	"point_light": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"colour": {
		  "$ref": "#/definitions/colour"
		},
		"fade_from": {
		  "type": "number"
		},
		"fade_to": {
		  "type": "number"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"colour",
		"fade_from",
		"fade_to"
	  ]
	},
	"direct_light": {
	  "type": "object",
	  "properties": {
		"position": {
		  "$ref": "#/definitions/vector3"
		},
		"colour": {
		  "$ref": "#/definitions/colour"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"position",
		"colour"
	  ]
	}
  },
  "type": "object",
  "properties": {
	"_meta": {
	  "type": "object",
	  "properties": {
		"version": {
		  "type": "integer"
		},
		"format": {
		  "enum": [
			"normal",
			"v12",
			"v12_old",
			"v12_old_noambient"
		  ]
		},
		"level": {
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 999
		},
		"sublevel": {
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 99
		},
		"checksum": {
		  "type": "integer"
		}
	  },
	  "additionalProperties": false,
	  "required": [
		"version",
		"format",
		"level",
		"sublevel",
		"checksum"
	  ]
	},
	"path": {
	  "$ref": "#/definitions/mapstring"
	},
	"name": {
	  "$ref": "#/definitions/mapstring"
	},
	"width": {
	  "$ref": "#/definitions/uint16"
	},
	"height": {
	  "$ref": "#/definitions/uint16"
	},
	"depth": {
	  "$ref": "#/definitions/uint16"
	},
	"style": {
	  "oneOf": [
		{
		  "enum": [
			"ice",
			"water",
			"castle",
			"desert",
			"cave",
			"wood",
			"dungeon",
			"boss1",
			"boss2",
			"boss3",
			"boss4",
			"boss5",
			"boss6",
			"boss7",
			"boss8",
			"boss9",
			"island1",
			"island2",
			"island3",
			"island4",
			"island5",
			"iceslide",
			"boulder",
			"icecave"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 24
		}
	  ]
	},
	"flags": {
	  "$ref": "#/definitions/uint32"
	},
	"cd_track": {
	  "$ref": "#/definitions/uint32"
	},
	"background": {
	  "$ref": "#/definitions/uint32"
	},
	"effect": {
	  "oneOf": [
		{
		  "enum": [
			"none",
			"snow",
			"fog",
			"torch",
			"torch_lightning",
			"torch_big",
			"torch_big_lightning",
			"dark",
			"snow_small",
			"snow_island",
			"torch_giant"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 15
		}
	  ]
	},
	"wait": {
	  "$ref": "#/definitions/uint32"
	},
	"ambience": {
	  "oneOf": [
		{
		  "enum": [
			"none",
			"bird",
			"drip",
			"nght",
			"watr",
			"crwd",
			"lava",
			"tunl",
			"ice1",
			"tomb",
			"des1",
			"dcav",
			"slde",
			"cast",
			"dngn",
			"ice2",
			"clwd",
			"whal",
			"moat",
			"dusk",
			"wind",
			"cica",
			"dant"
		  ]
		},
		{
		  "type": "integer",
		  "minimum": 0,
		  "maximum": 22
		}
	  ]
	},
	"start_rotation": {
	  "type": "number"
	},
	"tracks": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/track"
	  }
	},
	"strats": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/strategy"
	  }
	},
	"doors": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/door"
	  }
	},
	"point_lights": {
	  "type": "array",
	  "items": {
		"$ref": "#/definitions/point_light"
	  }
	},
	"direct_lights": {
	  "type": "array",
	  "minItems": 3,
	  "maxItems": 3,
	  "items": {
		"$ref": "#/definitions/direct_light"
	  }
	},
	"ambient_colour": {
	  "$ref": "#/definitions/colour"
	},
	"$schema": {
	  "type": "string"
	}
  },
  "additionalProperties": false,
  "required": [
	"path",
	"name",
	"width",
	"height",
	"depth",
	"style",
	"flags",
	"cd_track",
	"background",
	"effect",
	"wait",
	"ambience",
	"start_rotation",
	"tracks",
	"strats",
	"doors",
	"point_lights",
	"direct_lights",
	"ambient_colour"
  ]
}

=== vs49688/CrocUtils/resources/maps/json/pc/MP054_01.json
{
	"_meta":	{
		"version":	12,
		"format":	"v12_old",
		"level":	54,
		"sublevel":	1,
		"checksum":	0
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\ISLAND5\\LEVEL5\\MAP54_01.MAP",
	"name":	"avalanche escape 2",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"ice",
	"flags":	0,
	"cd_track":	29,
	"background":	17,
	"effect":	"none",
	"wait":	16,
	"ambience":	"none",
	"start_rotation":	-0.02197265625,
	"tracks":	[{
			"position":	[2, 0, 2],
			"yr":	0.25,
			"index":	42
		}, {
			"position":	[6, 0, 2],
			"yr":	0.5,
			"index":	39
		}, {
			"position":	[7, 0, 2],
			"yr":	0.25,
			"index":	39
		}, {
			"position":	[12, 0, 2],
			"yr":	0.75,
			"index":	42
		}, {
			"position":	[2, 0, 3],
			"yr":	0.25,
			"index":	42
		}, {
			"position":	[6, 0, 3],
			"yr":	0.75,
			"index":	39
		}, {
			"position":	[7, 0, 3],
			"yr":	0,
			"index":	39
		}, {
			"position":	[12, 0, 3],
			"yr":	0.75,
			"index":	42
		}, {
			"position":	[2, 0, 4],
			"yr":	0.25,
			"index":	42
		}, {
			"position":	[3, 0, 4],
			"yr":	0.5,
			"index":	39
		}, {
			"position":	[4, 0, 4],
			"yr":	0.25,
			"index":	39
		}, {
			"position":	[12, 0, 4],
			"yr":	0.75,
			"index":	42
		}, {
			"position":	[2, 0, 5],
			"yr":	0.25,
			"index":	44
		}, {
			"position":	[3, 0, 5],
			"yr":	0.75,
			"index":	39
		}, {
			"position":	[4, 0, 5],
			"yr":	0,
			"index":	39
		}, {
			"position":	[8, 2, 5],
			"yr":	0.5,
			"index":	62
		}, {
			"position":	[12, 0, 5],
			"yr":	0.75,
			"index":	43
		}, {
			"position":	[2, 0, 6],
			"yr":	0.25,
			"index":	45
		}, {
			"position":	[3, 0, 6],
			"yr":	0.25,
			"index":	39
		}, {
			"position":	[8, 0, 6],
			"yr":	0,
			"index":	58
		}, {
			"position":	[9, 0, 6],
			"yr":	0.25,
			"index":	61
		}, {
			"position":	[10, 0, 6],
			"yr":	0,
			"index":	61
		}, {
			"position":	[11, 0, 6],
			"yr":	0.5,
			"index":	39
		}, {
			"position":	[12, 0, 6],
			"yr":	0.75,
			"index":	46
		}, {
			"position":	[1, 0, 7],
			"yr":	0.25,
			"index":	73
		}, {
			"position":	[2, 0, 7],
			"yr":	0.25,
			"index":	72
		}, {
			"position":	[3, 0, 7],
			"yr":	0.25,
			"index":	37
		}, {
			"position":	[8, 0, 7],
			"yr":	0.5,
			"index":	61
		}, {
			"position":	[9, 0, 7],
			"yr":	0.75,
			"index":	61
		}, {
			"position":	[10, 0, 7],
			"yr":	0.5,
			"index":	61
		}, {
			"position":	[11, 0, 7],
			"yr":	0.75,
			"index":	65
		}, {
			"position":	[12, 0, 7],
			"yr":	0.75,
			"index":	72
		}, {
			"position":	[13, 0, 7],
			"yr":	0.75,
			"index":	73
		}, {
			"position":	[2, 0, 8],
			"yr":	0.25,
			"index":	46
		}, {
			"position":	[3, 0, 8],
			"yr":	0,
			"index":	39
		}, {
			"position":	[11, 0, 8],
			"yr":	0.75,
			"index":	39
		}, {
			"position":	[12, 0, 8],
			"yr":	0.75,
			"index":	45
		}, {
			"position":	[2, 0, 9],
			"yr":	0.25,
			"index":	43
		}, {
			"position":	[12, 0, 9],
			"yr":	0.75,
			"index":	44
		}, {
			"position":	[12, 0, 10],
			"yr":	0.75,
			"index":	42
		}],
	"strats":	[{
			"params":	[65536, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.28125, 0, 6.03125],
			"rotation":	[0, 0, 0],
			"name":	"PlatformCrumble",
			"waypoints":	[]
		}, {
			"params":	[65536, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.59375, 0, 5.46875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformCrumble",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.5, 0, 4.59375],
			"rotation":	[0, 0, 0],
			"name":	"FunkyMonkey",
			"waypoints":	[{
					"position":	[3.5, 0, 4.59375],
					"var":	327680
				}]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[6.46875, 0, 2.59375],
			"rotation":	[0, 0.846435546875, 0],
			"name":	"FunkyMonkey",
			"waypoints":	[{
					"position":	[6.46875, 0, 2.59375],
					"var":	262144
				}]
		}, {
			"params":	[0, 0, 0, 0, 131072, 0, 0, 0],
			"position":	[4.15625, 0, 3.96875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformNormal",
			"waypoints":	[{
					"position":	[4.15625, 0, 3.96875],
					"var":	0
				}, {
					"position":	[4.1875, 0, 3.1875],
					"var":	0
				}, {
					"position":	[4.96875, 0, 3.15625],
					"var":	0
				}, {
					"position":	[4.96875, 0, 3.96875],
					"var":	0
				}]
		}, {
			"params":	[0, 0, 65536, 0, 131072, 0, 0, 0],
			"position":	[5.71875, 0.17999267578125, 3.53125],
			"rotation":	[0, 0, 0],
			"name":	"PlatformNormal",
			"waypoints":	[{
					"position":	[5.71875, 0.1899871826171875, 3.53125],
					"var":	0
				}, {
					"position":	[5.53125, 0.16998291015625, 2.71875],
					"var":	0
				}, {
					"position":	[4.53125, 0.2199859619140625, 2.75],
					"var":	0
				}]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.53125, 0.399993896484375, 7.40625],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[2.53125, 0.6999969482421875, 7.40625],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[9.375, 0.2499847412109375, 6.09375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[9.625, 0.239990234375, 6.09375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[9.78125, 0.2599945068359375, 6.21875],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[9.84375, 0.269989013671875, 6.375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[9.9375, 0.2499847412109375, 6.59375],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[10.09375, 0.17999267578125, 6.71875],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[10.25, 0.1299896240234375, 6.8125],
			"rotation":	[0, 0, 0],
			"name":	"Crystal",
			"waypoints":	[]
		}, {
			"params":	[65536, 0, 0, 0, 0, 0, 0, 0],
			"position":	[7.9375, 0.29998779296875, 4.51373291015625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformCrumble",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[10.25, -0.29998779296875, 5.28125],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[10.25, -0.1299896240234375, 5.28125],
			"rotation":	[0, 0, 0],
			"name":	"Gobbo",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 655360, 65536, 0, 0, 0],
			"position":	[8.375, 0, 2.625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformSpin",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[8.5, 0, 4.4375],
			"rotation":	[0, 0, 0],
			"name":	"PlatformCrumble",
			"waypoints":	[]
		}],
	"doors":	[{
			"position":	[1, 0, 7],
			"level":	54,
			"sublevel":	0,
			"flags":	["normal", "start"],
			"id":	0
		}, {
			"position":	[13, 0, 7],
			"level":	54,
			"sublevel":	2,
			"flags":	["normal"],
			"id":	0
		}],
	"point_lights":	[{
			"position":	[147, 7.9998779296875, -1.0999908447265625],
			"colour":	[140, 255, 255],
			"fade_from":	0.001953125,
			"fade_to":	26368.005859375
		}, {
			"position":	[10495.99609375, 26368.04296875, -20736.00390625],
			"colour":	[255, 242, 0],
			"fade_from":	-32768,
			"fade_to":	1.52587890625e-05
		}],
	"direct_lights":	[{
			"position":	[1, 0, 0],
			"colour":	[64, 0, 0]
		}, {
			"position":	[0.5, 0.865966796875, 0],
			"colour":	[128, 0, 0]
		}, {
			"position":	[0.5, -0.000244140625, 0],
			"colour":	[43, 0, 16]
		}],
	"ambient_colour":	[56, 0, 33]
}

=== vs49688/CrocUtils/resources/maps/json/slus00530/MP042_02.json
{
	"_meta":	{
		"version":	20,
		"format":	"normal",
		"level":	42,
		"sublevel":	2,
		"checksum":	28986
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\GAME\\CASTLE\\LEVEL3\\MAP3.MAP",
	"name":	"Default New Map",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"dungeon",
	"flags":	0,
	"cd_track":	34,
	"background":	0,
	"effect":	"none",
	"wait":	0,
	"ambience":	"wind",
	"start_rotation":	0.013671875,
	"tracks":	[{
			"position":	[3, 0, 0],
			"yr":	0,
			"index":	16
		}, {
			"position":	[1, 0, 1],
			"yr":	0,
			"index":	13
		}, {
			"position":	[2, 0, 1],
			"yr":	0,
			"index":	0
		}, {
			"position":	[3, 0, 1],
			"yr":	0,
			"index":	15
		}, {
			"position":	[4, 0, 1],
			"yr":	0,
			"index":	0
		}, {
			"position":	[5, 0, 1],
			"yr":	0.75,
			"index":	13
		}, {
			"position":	[1, 0, 2],
			"yr":	0.25,
			"index":	0
		}, {
			"position":	[2, 0, 2],
			"yr":	0,
			"index":	3
		}, {
			"position":	[3, 0, 2],
			"yr":	0,
			"index":	3
		}, {
			"position":	[4, 0, 2],
			"yr":	0,
			"index":	3
		}, {
			"position":	[5, 0, 2],
			"yr":	0.75,
			"index":	0
		}, {
			"position":	[1, 0, 3],
			"yr":	0.25,
			"index":	0
		}, {
			"position":	[2, 0, 3],
			"yr":	0,
			"index":	3
		}, {
			"position":	[3, 0, 3],
			"yr":	0,
			"index":	11
		}, {
			"position":	[4, 0, 3],
			"yr":	0,
			"index":	3
		}, {
			"position":	[5, 0, 3],
			"yr":	0.75,
			"index":	0
		}, {
			"position":	[1, 0, 4],
			"yr":	0.25,
			"index":	0
		}, {
			"position":	[2, 0, 4],
			"yr":	0,
			"index":	3
		}, {
			"position":	[3, 0, 4],
			"yr":	0,
			"index":	3
		}, {
			"position":	[4, 0, 4],
			"yr":	0,
			"index":	3
		}, {
			"position":	[5, 0, 4],
			"yr":	0.75,
			"index":	0
		}, {
			"position":	[1, 0, 5],
			"yr":	0.25,
			"index":	13
		}, {
			"position":	[2, 0, 5],
			"yr":	0.5,
			"index":	0
		}, {
			"position":	[3, 0, 5],
			"yr":	0.5,
			"index":	15
		}, {
			"position":	[4, 0, 5],
			"yr":	0.5,
			"index":	0
		}, {
			"position":	[5, 0, 5],
			"yr":	0.5,
			"index":	13
		}, {
			"position":	[3, 0, 6],
			"yr":	0.5,
			"index":	16
		}],
	"strats":	[{
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[48, 0, 7.179931640625],
			"rotation":	[0, 0, 0],
			"name":	"OneWayDoor",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[48, 0, 88.519775390625],
			"rotation":	[0, 0.49951171875, 0],
			"name":	"NormalDoor",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[72, 0, 48],
			"rotation":	[0, 0, 0],
			"name":	"ChaseMeBlock",
			"waypoints":	[{
					"position":	[78, 0, 80.5],
					"var":	0
				}, {
					"position":	[16, 0, 17],
					"var":	0
				}]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[48, -1.599853515625, 48.5],
			"rotation":	[0, 0.49951171875, 0],
			"name":	"SpookySpider",
			"waypoints":	[]
		}, {
			"params":	[655360, 0, 0, 0, 0, 0, 0, 0],
			"position":	[72, -1.599853515625, 71.89990234375],
			"rotation":	[0, 0.610595703125, 0],
			"name":	"SpookySpider",
			"waypoints":	[]
		}, {
			"params":	[1310720, 0, 0, 0, 0, 0, 0, 0],
			"position":	[24.39990234375, -1.599853515625, 71.89990234375],
			"rotation":	[0, 0.37451171875, 0],
			"name":	"SpookySpider",
			"waypoints":	[]
		}, {
			"params":	[1966080, 0, 0, 0, 0, 0, 0, 0],
			"position":	[24.39990234375, -1.599853515625, 24.89990234375],
			"rotation":	[0, 0.124755859375, 0],
			"name":	"SpookySpider",
			"waypoints":	[]
		}, {
			"params":	[2621440, 0, 0, 0, 0, 0, 0, 0],
			"position":	[72, -1.599853515625, 25.39990234375],
			"rotation":	[0, 0.8603515625, 0],
			"name":	"SpookySpider",
			"waypoints":	[]
		}],
	"doors":	[{
			"position":	[3, 0, 0],
			"level":	42,
			"sublevel":	1,
			"flags":	["normal"],
			"id":	0
		}, {
			"position":	[3, 0, 1],
			"level":	0,
			"sublevel":	0,
			"flags":	["start"],
			"id":	0
		}, {
			"position":	[3, 0, 6],
			"level":	42,
			"sublevel":	3,
			"flags":	["normal"],
			"id":	0
		}],
	"point_lights":	[{
			"position":	[1, 0, 1.09375],
			"colour":	[174, 107, 255],
			"fade_from":	1,
			"fade_to":	2
		}, {
			"position":	[1, 0, 4.96875],
			"colour":	[255, 255, 102],
			"fade_from":	1,
			"fade_to":	2
		}, {
			"position":	[4.875, 0, 5],
			"colour":	[102, 179, 95],
			"fade_from":	1,
			"fade_to":	2
		}, {
			"position":	[4.875, 0, 1.1875],
			"colour":	[104, 75, 148],
			"fade_from":	1,
			"fade_to":	2
		}, {
			"position":	[3, 0, 3.0625],
			"colour":	[255, 255, 79],
			"fade_from":	1,
			"fade_to":	2
		}],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[64, 64, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 128]
		}, {
			"position":	[0, 0.5, -0.000244140625],
			"colour":	[43, 43, 43]
		}],
	"ambient_colour":	[43, 39, 39]
}

=== vs49688/CrocUtils/resources/maps/json/beta012/MP002_02.json
{
	"_meta":	{
		"version":	12,
		"format":	"v12_old",
		"level":	2,
		"sublevel":	2,
		"checksum":	0
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\LEWIS\\MAP3.MAP",
	"name":	"Default New Map",
	"width":	16,
	"height":	16,
	"depth":	32,
	"style":	"desert",
	"flags":	0,
	"cd_track":	0,
	"background":	0,
	"effect":	"none",
	"wait":	0,
	"ambience":	"none",
	"start_rotation":	-0.0341796875,
	"tracks":	[{
			"position":	[2, 0, 1],
			"yr":	0.25,
			"index":	6
		}, {
			"position":	[3, 0, 1],
			"yr":	0,
			"index":	5
		}, {
			"position":	[4, 0, 1],
			"yr":	0,
			"index":	5
		}, {
			"position":	[5, 0, 1],
			"yr":	0,
			"index":	6
		}, {
			"position":	[2, 0, 2],
			"yr":	0.25,
			"index":	5
		}, {
			"position":	[3, 0, 2],
			"yr":	0,
			"index":	37
		}, {
			"position":	[4, 0, 2],
			"yr":	0,
			"index":	37
		}, {
			"position":	[5, 0, 2],
			"yr":	0.75,
			"index":	7
		}, {
			"position":	[6, 0, 2],
			"yr":	0,
			"index":	6
		}, {
			"position":	[2, 0, 3],
			"yr":	0.25,
			"index":	5
		}, {
			"position":	[3, 0, 3],
			"yr":	0.5,
			"index":	22
		}, {
			"position":	[4, 0, 3],
			"yr":	0.5,
			"index":	12
		}, {
			"position":	[5, 0, 3],
			"yr":	0.25,
			"index":	22
		}, {
			"position":	[6, 0, 3],
			"yr":	0.75,
			"index":	5
		}, {
			"position":	[2, 0, 4],
			"yr":	0.25,
			"index":	5
		}, {
			"position":	[3, 0, 4],
			"yr":	0.75,
			"index":	12
		}, {
			"position":	[5, 0, 4],
			"yr":	0.25,
			"index":	12
		}, {
			"position":	[6, 0, 4],
			"yr":	0.75,
			"index":	5
		}, {
			"position":	[2, 0, 5],
			"yr":	0.25,
			"index":	5
		}, {
			"position":	[3, 0, 5],
			"yr":	0.75,
			"index":	22
		}, {
			"position":	[4, 0, 5],
			"yr":	0,
			"index":	12
		}, {
			"position":	[5, 0, 5],
			"yr":	0,
			"index":	22
		}, {
			"position":	[6, 0, 5],
			"yr":	0.75,
			"index":	5
		}, {
			"position":	[2, 0, 6],
			"yr":	0.5,
			"index":	6
		}, {
			"position":	[3, 0, 6],
			"yr":	0.5,
			"index":	5
		}, {
			"position":	[4, 0, 6],
			"yr":	0.5,
			"index":	5
		}, {
			"position":	[5, 0, 6],
			"yr":	0.5,
			"index":	5
		}, {
			"position":	[6, 0, 6],
			"yr":	0.75,
			"index":	6
		}, {
			"position":	[3, 8, 3],
			"yr":	0.5,
			"index":	80
		}, {
			"position":	[4, 8, 3],
			"yr":	0.5,
			"index":	78
		}, {
			"position":	[5, 8, 3],
			"yr":	0.25,
			"index":	80
		}, {
			"position":	[3, 8, 4],
			"yr":	0.75,
			"index":	78
		}, {
			"position":	[4, 8, 4],
			"yr":	0,
			"index":	37
		}, {
			"position":	[5, 8, 4],
			"yr":	0.25,
			"index":	78
		}, {
			"position":	[3, 8, 5],
			"yr":	0.75,
			"index":	80
		}, {
			"position":	[4, 8, 5],
			"yr":	0,
			"index":	78
		}, {
			"position":	[5, 8, 5],
			"yr":	0,
			"index":	80
		}],
	"strats":	[{
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[3.71875, 0.17999267578125, 2.03125],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.34375, 0.5, 2.0625],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}, {
			"params":	[0, 0, 0, 0, 0, 0, 0, 0],
			"position":	[4.78125, 0.8499908447265625, 2.342498779296875],
			"rotation":	[0, 0, 0],
			"name":	"PlatformDead",
			"waypoints":	[]
		}],
	"doors":	[{
			"position":	[3, 0, 2],
			"level":	0,
			"sublevel":	0,
			"flags":	["start"],
			"id":	0
		}, {
			"position":	[4, 0, 2],
			"level":	0,
			"sublevel":	0,
			"flags":	[],
			"id":	0
		}],
	"point_lights":	[],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[64, 64, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 128]
		}, {
			"position":	[0, 0.5, -0.000244140625],
			"colour":	[43, 43, 43]
		}],
	"ambient_colour":	[64, 64, 64]
}

=== vs49688/CrocUtils/resources/maps/json/beta012/MP003_02.json
{
	"_meta":	{
		"version":	12,
		"format":	"v12_old",
		"level":	0,
		"sublevel":	2,
		"checksum":	0
	},
	"path":	"P:\\CROC\\EDITOR\\MAPS\\TONY\\SNOWTEST.MAP",
	"name":	"Snow Test",
	"width":	3,
	"height":	3,
	"depth":	1,
	"style":	"ice",
	"flags":	0,
	"cd_track":	0,
	"background":	0,
	"effect":	"snow",
	"wait":	16,
	"ambience":	"none",
	"start_rotation":	0,
	"tracks":	[{
			"position":	[0, 0, 0],
			"yr":	0.25,
			"index":	30
		}, {
			"position":	[1, 0, 0],
			"yr":	0,
			"index":	28
		}, {
			"position":	[2, 0, 0],
			"yr":	0,
			"index":	30
		}, {
			"position":	[0, 0, 1],
			"yr":	0.25,
			"index":	28
		}, {
			"position":	[1, 0, 1],
			"yr":	0.5,
			"index":	6
		}, {
			"position":	[2, 0, 1],
			"yr":	0.75,
			"index":	28
		}, {
			"position":	[0, 0, 2],
			"yr":	0.5,
			"index":	30
		}, {
			"position":	[1, 0, 2],
			"yr":	0.5,
			"index":	28
		}, {
			"position":	[2, 0, 2],
			"yr":	0.75,
			"index":	30
		}],
	"strats":	[],
	"doors":	[{
			"position":	[1, 0, 1],
			"level":	0,
			"sublevel":	0,
			"flags":	["start"],
			"id":	0
		}],
	"point_lights":	[],
	"direct_lights":	[{
			"position":	[0, 1, 0],
			"colour":	[64, 64, 64]
		}, {
			"position":	[0, 0.5, 0.865966796875],
			"colour":	[255, 255, 128]
		}, {
			"position":	[0, 0.5, -0.865966796875],
			"colour":	[43, 43, 43]
		}],
	"ambient_colour":	[64, 64, 64]
}
